=== Emiliyana/XML2016/4/Stats.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT mancala (svg,pits,seed,stores,layout)>
<!ELEMENT svg (width,height)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>

<!ELEMENT pits (width,height,roundX,roundY,style,pitCount,nrOfSeedsReset,top,bot)>
<!ELEMENT roundX (#PCDATA)>
<!ELEMENT roundY (#PCDATA)>
<!ELEMENT style (#PCDATA)>
<!ELEMENT pitCount (#PCDATA)>
<!ELEMENT nrOfSeedsReset (#PCDATA)>
<!ELEMENT top (pit)*>
<!ELEMENT pit (#PCDATA)>
<!ELEMENT bot (pit)*>

<!ELEMENT seed (style)>

<!ELEMENT stores (radius,style,textstyle,(store*))>
<!ELEMENT radius (#PCDATA)>
<!ELEMENT textstyle (#PCDATA)>
<!ELEMENT store (#PCDATA)>

<!ELEMENT layout (posStartX,posStartY,distanceHouseX,distanceHouseY,distanceHouseStore,distanceYextraSeeds,distanceBetweenExtraSeeds,lengthUnit,players)>
<!ELEMENT posStartX (#PCDATA)>
<!ELEMENT posStartY (#PCDATA)>
<!ELEMENT distanceHouseX (#PCDATA)>
<!ELEMENT distanceHouseY (#PCDATA)>
<!ELEMENT distanceHouseStore (#PCDATA)>
<!ELEMENT distanceYextraSeeds (#PCDATA)>
<!ELEMENT distanceBetweenExtraSeeds (#PCDATA)>
<!ELEMENT lengthUnit (#PCDATA)>
<!ELEMENT players (playerTurn,highestScore,(player*))>
<!ELEMENT playerTurn (#PCDATA)>
<!ELEMENT highestScore (#PCDATA)>
<!ELEMENT player (name,currScore)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT currScore (#PCDATA)>

=== Emiliyana/XML2016/4/Stats.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mancala SYSTEM "Stats.dtd">
<?xml-stylesheet href="Transform.xsl" type="text/xsl"?>
<mancala>
    <svg>
        <width>5000</width>
        <height>5000</height>
    </svg>
    <pits>
        <width>100</width>
        <height>100</height>
        <roundX>10</roundX>
        <roundY>10</roundY>
        <style>fill:white;stroke:black;stroke-width:2;</style>
        <pitCount>6</pitCount>
        <nrOfSeedsReset>3</nrOfSeedsReset>
        <top>
            <pit>1</pit>
            <pit>2</pit>
            <pit>3</pit>
            <pit>4</pit>
            <pit>5</pit>
            <pit>6</pit>
        </top>
        <bot>
            <pit>6</pit>
            <pit>5</pit>
            <pit>4</pit>
            <pit>3</pit>
            <pit>2</pit>
            <pit>1</pit>
        </bot>
    </pits>
    <seed>
        <style>fill:black;</style>
    </seed>
    <houses>	
        <radius>100</radius>
        <style>fill:white;stroke:black;stroke-width:2;</style>
        <textstyle>fill:black;font-weight:bold;font-family:Agency FB;</textstyle>
        <house>20</house>
        <house>100</house>
    </houses>
    <layout>
        <posStartX>150</posStartX>
        <posStartY>150</posStartY>
        <distancePitX>15</distancePitX>
        <distancePitY>50</distancePitY>
        <distancePitStore>15</distancePitStore>
        <distanceYextraSeeds>8</distanceYextraSeeds>
        <distanceBetweenExtraSeeds>5</distanceBetweenExtraSeeds>
        <lengthUnit>px</lengthUnit>
        <players>
            <playerTurn>up</playerTurn>
            <highestScore>1000</highestScore>
            <player>
                <name>A</name>
                <currScore>500</currScore>
            </player>
            <player>
                <name>B</name>
                <currScore>800</currScore>
            </player>
        </players>		
    </layout>
</mancala>
